export default [
  "Brick quiz whangs jumpy veldt fox!",
  "Quick wafting zephyrs vex bold Jim.",
  "The five boxing wizards jump quickly.",
  "Jackdaws love my sphinx of black quartz.",
  "The five boxing wizards jumped quickly.",
  "Five big quacking zephyrs jolt my wax bed.",
  "Hick Jed wins quiz for extra blimp voyage.",
  "Sympathizing would fix Quaker objectives.",
  "Many-wived Jack laughs at probes of sex quiz.",
  "Mix Zapf with Veljovic and get quirky Beziers.",
  "Brawny gods just flocked up to quiz and vex him.",
  "Jim just quit and packed extra bags for Liz Owen.",
  "Turgid saxophones blew over Mick's jazzy quaff.",
  "Dumpy kibitzer jingles as exchequer overflows.",
  "Puzzled women bequeath jerks very exotic gifts.",
  "Playing jazz vibe chords quickly excites my wife.",
  "A boy, Max, felt quick during his hazy weaving jumps.",
  "A large fawn jumped quickly over white zinc boxes.",
  "Viewing quizzical abstracts mixed up hefty jocks.",
  "Five wine experts jokingly quizzed sample Chablis.",
  "William Jex quickly caught five dozen Republicans.",
  "The vixen jumped quickly on her foe barking with zeal.",
  "Harry, jogging quickly, axed zen monks with beef vapor.",
  "Five or six big jet planes zoomed quickly by the tower.",
  "Six big devils from Japan quickly forgot how to waltz.",
  "Big July earthquakes confound zany experimental vow.",
  "Exquisite farm wench gives body jolt to prize stinker.",
  "My grandfather picks up quartz and valuable onyx jewels.",
  "Six crazy kings vowed to abolish my quite pitiful jousts.",
  "Jack amazed a few girls by dropping the antique onyx vase!",
  "We have just quoted on nine dozen boxes of gray lamp wicks.",
  "Jay visited back home and gazed upon a brown fox and quail.",
  "May Jo equal the fine record by solving six puzzles a week?",
  "Fred specialized in the job of making very quaint wax toys.",
  "Freight to me sixty dozen quart jars and twelve black pans.",
  "Jeb quickly drove a few extra miles on the glazed pavement.",
  "Grumpy wizards make toxic brew for the evil Queen and Jack.",
  "Verily the dark ex-Jew quit Zionism, preferring the cabala.",
  "The job of waxing linoleum frequently peeves chintzy kids.",
  "West quickly gave Bert handsome prizes for six juicy plums.",
  "Just keep examining every low bid quoted for zinc etchings.",
  "A quick movement of the enemy will jeopardize six gunboats.",
  "All questions asked by five watch experts amazed the judge.",
  "The exodus of jazzy pigeons is craved by squeamish walkers."
];
